import { SoundRecipe } from '@/types/recipe';
import { validateRecipe } from '../synthesis/validation';

/**
 * Validates and serializes a SoundRecipe as pretty-printed JSON.
 */
export function generateReadableJson(recipe: SoundRecipe): string {
  const validation = validateRecipe(recipe);
  if (!validation.valid) {
    throw new Error(`Invalid recipe: ${validation.errors.join(', ')}`);
  }
  return JSON.stringify(recipe, null, 2);
}

/**
 * Validates and serializes a SoundRecipe as compact, minified JSON.
 */
export function generateMinifiedJson(recipe: SoundRecipe): string {
  const validation = validateRecipe(recipe);
  if (!validation.valid) {
    throw new Error(`Invalid recipe: ${validation.errors.join(', ')}`);
  }
  return JSON.stringify(recipe);
}

/**
 * Generates a standalone, zero-dependency JavaScript module with Web Audio playback.
 */
export function generateStandaloneJs(recipe: SoundRecipe): string {
  const minifiedRecipe = JSON.stringify(recipe);

  return `/**
 * Standalone Procedural Audio Player for "${recipe.name}"
 * Generated by Resonance SFX (Local-First Web Audio Synth)
 * Zero external dependencies. Uses standard Web Audio API.
 */

export const recipe = ${minifiedRecipe};

function createDeterministicRng(seed) {
  let s = seed | 0;
  return function() {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function createNoiseBuffer(ctx, duration, seed) {
  const length = Math.max(1, Math.floor(ctx.sampleRate * duration));
  const buffer = ctx.createBuffer(1, length, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  const rng = createDeterministicRng(seed);
  for (let i = 0; i < length; i++) {
    data[i] = rng() * 2 - 1;
  }
  return buffer;
}

function createDistortionCurve(amount) {
  const k = (amount * 50) / (1 - Math.min(amount, 0.99) * 0.5);
  const samples = 512;
  const curve = new Float32Array(samples);
  const deg = Math.PI / 180;
  for (let i = 0; i < samples; ++i) {
    const x = (i * 2) / samples - 1;
    curve[i] = k === 0 ? x : ((3 + k) * x * 20 * deg) / (Math.PI + k * Math.abs(x));
  }
  return curve;
}

/**
 * Plays the procedural sound effect.
 * @param {AudioContext|BaseAudioContext} [ctx] - Optional AudioContext instance. Creates one if omitted.
 * @param {Object} [options]
 * @param {number} [options.volume=1.0] - Master playback volume multiplier.
 * @param {AudioNode} [options.destination] - Destination node to connect to (defaults to ctx.destination).
 * @returns {{ stop: () => void, duration: number }} Playback control handle.
 */
export function playSound(ctx, options = {}) {
  const audioCtx = ctx || new (window.AudioContext || window.webkitAudioContext)();
  if (audioCtx.state === 'suspended') {
    audioCtx.resume();
  }

  const destination = options.destination || audioCtx.destination;
  const masterVolume = options.volume !== undefined ? options.volume : 1.0;
  const now = audioCtx.currentTime;

  const masterGain = audioCtx.createGain();
  masterGain.gain.setValueAtTime((recipe.masterGain ?? 0.8) * masterVolume, now);

  const limiter = audioCtx.createDynamicsCompressor();
  limiter.threshold.setValueAtTime(-1, now);
  masterGain.connect(limiter);
  limiter.connect(destination);

  const anySolo = recipe.layers.some(l => l.solo);

  recipe.layers.forEach(layer => {
    if (!layer.enabled) return;
    if (anySolo && !layer.solo) return;

    const tStart = now + layer.startTime;
    const dur = Math.max(0.005, layer.duration);
    const tEnd = tStart + dur;

    let source;
    if (layer.oscillatorType === 'noise') {
      source = audioCtx.createBufferSource();
      source.buffer = createNoiseBuffer(audioCtx, dur, layer.seed || 123);
    } else {
      source = audioCtx.createOscillator();
      source.type = layer.oscillatorType;
      source.frequency.setValueAtTime(layer.startFrequency, tStart);
      if (layer.frequencyCurve === 'exponential') {
        source.frequency.exponentialRampToValueAtTime(Math.max(10, layer.endFrequency), tEnd);
      } else if (layer.frequencyCurve === 'linear') {
        source.frequency.linearRampToValueAtTime(layer.endFrequency, tEnd);
      }
    }

    const env = audioCtx.createGain();
    const peak = layer.gain;
    const sust = peak * (layer.envelope.sustain ?? 0);
    const atk = Math.min(layer.envelope.attack, dur * 0.3);
    const dec = Math.min(layer.envelope.decay, dur * 0.5);

    env.gain.setValueAtTime(0.0001, tStart);
    env.gain.linearRampToValueAtTime(peak, tStart + atk);
    env.gain.exponentialRampToValueAtTime(Math.max(0.0001, sust), tStart + atk + dec);
    env.gain.linearRampToValueAtTime(0.00001, tEnd);

    source.connect(env);
    let chain = env;

    if (layer.lowPassFilter && layer.lowPassFilter.enabled) {
      const lp = audioCtx.createBiquadFilter();
      lp.type = 'lowpass';
      lp.frequency.setValueAtTime(layer.lowPassFilter.cutoff, tStart);
      lp.Q.setValueAtTime(layer.lowPassFilter.q || 1, tStart);
      chain.connect(lp);
      chain = lp;
    }

    if (layer.distortion && layer.distortion.enabled && layer.distortion.amount > 0.01) {
      const dist = audioCtx.createWaveShaper();
      dist.curve = createDistortionCurve(layer.distortion.amount);
      chain.connect(dist);
      chain = dist;
    }

    chain.connect(masterGain);
    source.start(tStart);
    source.stop(tEnd);
  });

  return {
    duration: recipe.duration,
    stop: () => {
      masterGain.gain.setValueAtTime(masterGain.gain.value, audioCtx.currentTime);
      masterGain.gain.linearRampToValueAtTime(0.00001, audioCtx.currentTime + 0.05);
    }
  };
}
`;
}

/**
 * Generates a standalone, fully-typed TypeScript module.
 */
export function generateStandaloneTs(recipe: SoundRecipe): string {
  const jsContent = generateStandaloneJs(recipe);
  return (
    `import type { SoundRecipe } from '@/types/recipe';\n\n` +
    jsContent.replace('export const recipe =', 'export const recipe: SoundRecipe =').replace(
      'export function playSound(ctx, options = {})',
      `export interface PlaySoundOptions {
  volume?: number;
  destination?: AudioNode;
}

export function playSound(
  ctx?: BaseAudioContext,
  options: PlaySoundOptions = {}
): { duration: number; stop: () => void }`
    )
  );
}

/**
 * Generates a runtime bundle containing player, types, recipe JSON, and documentation.
 */
export function generateRuntimePackage(recipe: SoundRecipe): Record<string, string> {
  const tsPlayer = generateStandaloneTs(recipe);
  const jsonRecipe = generateReadableJson(recipe);

  const readme = `# Procedural Audio Runtime - ${recipe.name}

Generated with **Resonance SFX** — Local-first browser audio synthesizer.

## Quick Start (JavaScript / TypeScript)

\`\`\`typescript
import { playSound } from './player';

// Trigger anywhere upon user interaction:
const handle = playSound();
console.log('Playing sound effect, duration:', handle.duration);
\`\`\`

## Specs

- **Recipe Name**: ${recipe.name}
- **Category**: ${recipe.category ?? 'Sound Effect'}
- **Duration**: ${recipe.duration.toFixed(3)}s
- **Layer Count**: ${recipe.layers.length}
- **Audio Engine**: Web Audio API standard synthesis
`;

  const license = `Mozilla Public License Version 2.0
Generated audio recipes and runtime code are open to use in personal and commercial game projects without royalties.`;

  return {
    'recipe.sfx.json': jsonRecipe,
    'player.ts': tsPlayer,
    'README.md': readme,
    LICENSE: license,
  };
}
