import { SoundRecipe } from '@/types/recipe';

export const BUILT_IN_EXAMPLES: Record<string, SoundRecipe> = {
  'ui-click': {
    version: 1,
    name: 'UI Click',
    category: 'Interface',
    duration: 0.06,
    masterGain: 0.75,
    metadata: {
      createdAt: new Date().toISOString(),
      generator: 'Built-in Procedural Preset',
      classification: 'percussive',
    },
    layers: [
      {
        id: 'click-transient',
        name: 'Transient Pop',
        enabled: true,
        solo: false,
        oscillatorType: 'sine',
        startTime: 0,
        duration: 0.035,
        gain: 0.85,
        pan: 0,
        startFrequency: 2200,
        endFrequency: 450,
        frequencyCurve: 'exponential',
        envelope: { attack: 0.001, decay: 0.02, sustain: 0.0, release: 0.01 },
        lowPassFilter: { enabled: false, cutoff: 8000, q: 1 },
        highPassFilter: { enabled: true, cutoff: 400, q: 0.7 },
        distortion: { enabled: false, amount: 0 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 100, modDepth: 0 },
        seed: 42,
      },
      {
        id: 'click-tick',
        name: 'High Tick',
        enabled: true,
        solo: false,
        oscillatorType: 'noise',
        startTime: 0,
        duration: 0.015,
        gain: 0.45,
        pan: 0,
        startFrequency: 5000,
        endFrequency: 5000,
        frequencyCurve: 'constant',
        envelope: { attack: 0.001, decay: 0.008, sustain: 0.0, release: 0.005 },
        lowPassFilter: { enabled: true, cutoff: 12000, q: 1 },
        highPassFilter: { enabled: true, cutoff: 3500, q: 1.5 },
        distortion: { enabled: false, amount: 0 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 100, modDepth: 0 },
        seed: 991,
      },
    ],
  },

  'coin-pickup': {
    version: 1,
    name: 'Coin Pickup',
    category: 'Item',
    duration: 0.38,
    masterGain: 0.7,
    metadata: {
      createdAt: new Date().toISOString(),
      generator: 'Built-in Procedural Preset',
      classification: 'tonal',
    },
    layers: [
      {
        id: 'coin-step-1',
        name: 'Step 1 (B5)',
        enabled: true,
        solo: false,
        oscillatorType: 'sine',
        startTime: 0,
        duration: 0.09,
        gain: 0.75,
        pan: -0.1,
        startFrequency: 987.77, // B5
        endFrequency: 987.77,
        frequencyCurve: 'constant',
        envelope: { attack: 0.002, decay: 0.06, sustain: 0.2, release: 0.02 },
        lowPassFilter: { enabled: false, cutoff: 10000, q: 1 },
        highPassFilter: { enabled: false, cutoff: 100, q: 1 },
        distortion: { enabled: false, amount: 0 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 100, modDepth: 0 },
        seed: 1234,
      },
      {
        id: 'coin-step-2',
        name: 'Step 2 (E6)',
        enabled: true,
        solo: false,
        oscillatorType: 'sine',
        startTime: 0.085,
        duration: 0.28,
        gain: 0.8,
        pan: 0.1,
        startFrequency: 1318.51, // E6
        endFrequency: 1318.51,
        frequencyCurve: 'constant',
        envelope: { attack: 0.002, decay: 0.18, sustain: 0.05, release: 0.08 },
        lowPassFilter: { enabled: false, cutoff: 10000, q: 1 },
        highPassFilter: { enabled: false, cutoff: 100, q: 1 },
        distortion: { enabled: false, amount: 0 },
        delay: { enabled: true, time: 0.07, feedback: 0.25, mix: 0.2 },
        frequencyModulation: { enabled: false, modFrequency: 100, modDepth: 0 },
        seed: 5678,
      },
      {
        id: 'coin-harmonic',
        name: 'Shimmer Sparkle',
        enabled: true,
        solo: false,
        oscillatorType: 'triangle',
        startTime: 0.085,
        duration: 0.25,
        gain: 0.35,
        pan: 0.2,
        startFrequency: 2637.02, // E7 octave harmonic
        endFrequency: 2637.02,
        frequencyCurve: 'constant',
        envelope: { attack: 0.005, decay: 0.12, sustain: 0.0, release: 0.06 },
        lowPassFilter: { enabled: false, cutoff: 12000, q: 1 },
        highPassFilter: { enabled: true, cutoff: 1500, q: 1 },
        distortion: { enabled: false, amount: 0 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 100, modDepth: 0 },
        seed: 9101,
      },
    ],
  },

  laser: {
    version: 1,
    name: 'Laser',
    category: 'Combat',
    duration: 0.24,
    masterGain: 0.72,
    metadata: {
      createdAt: new Date().toISOString(),
      generator: 'Built-in Procedural Preset',
      classification: 'tonal',
    },
    layers: [
      {
        id: 'laser-sweep',
        name: 'Saw Sweep Down',
        enabled: true,
        solo: false,
        oscillatorType: 'sawtooth',
        startTime: 0,
        duration: 0.22,
        gain: 0.8,
        pan: 0,
        startFrequency: 1750,
        endFrequency: 120,
        frequencyCurve: 'exponential',
        envelope: { attack: 0.002, decay: 0.15, sustain: 0.1, release: 0.05 },
        lowPassFilter: { enabled: true, cutoff: 4500, q: 3.5 },
        highPassFilter: { enabled: true, cutoff: 80, q: 1 },
        distortion: { enabled: true, amount: 0.15 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 80, modDepth: 0 },
        seed: 456,
      },
      {
        id: 'laser-zap',
        name: 'Square Sub-sweep',
        enabled: true,
        solo: false,
        oscillatorType: 'square',
        startTime: 0,
        duration: 0.16,
        gain: 0.5,
        pan: 0,
        startFrequency: 1200,
        endFrequency: 240,
        frequencyCurve: 'exponential',
        envelope: { attack: 0.003, decay: 0.1, sustain: 0.0, release: 0.04 },
        lowPassFilter: { enabled: true, cutoff: 3000, q: 2 },
        highPassFilter: { enabled: false, cutoff: 100, q: 1 },
        distortion: { enabled: false, amount: 0 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 120, modDepth: 0 },
        seed: 789,
      },
    ],
  },

  jump: {
    version: 1,
    name: 'Jump',
    category: 'Movement',
    duration: 0.28,
    masterGain: 0.75,
    metadata: {
      createdAt: new Date().toISOString(),
      generator: 'Built-in Procedural Preset',
      classification: 'tonal',
    },
    layers: [
      {
        id: 'jump-rise',
        name: 'Square Rise Up',
        enabled: true,
        solo: false,
        oscillatorType: 'square',
        startTime: 0,
        duration: 0.26,
        gain: 0.7,
        pan: 0,
        startFrequency: 140,
        endFrequency: 680,
        frequencyCurve: 'exponential',
        envelope: { attack: 0.005, decay: 0.18, sustain: 0.2, release: 0.06 },
        lowPassFilter: { enabled: true, cutoff: 2400, q: 2 },
        highPassFilter: { enabled: false, cutoff: 80, q: 1 },
        distortion: { enabled: false, amount: 0 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 50, modDepth: 0 },
        seed: 332,
      },
      {
        id: 'jump-body',
        name: 'Sine Sub Rise',
        enabled: true,
        solo: false,
        oscillatorType: 'sine',
        startTime: 0,
        duration: 0.22,
        gain: 0.75,
        pan: 0,
        startFrequency: 120,
        endFrequency: 480,
        frequencyCurve: 'linear',
        envelope: { attack: 0.003, decay: 0.15, sustain: 0.15, release: 0.05 },
        lowPassFilter: { enabled: false, cutoff: 4000, q: 1 },
        highPassFilter: { enabled: false, cutoff: 50, q: 1 },
        distortion: { enabled: false, amount: 0 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 50, modDepth: 0 },
        seed: 333,
      },
    ],
  },

  hit: {
    version: 1,
    name: 'Hit',
    category: 'Combat',
    duration: 0.22,
    masterGain: 0.78,
    metadata: {
      createdAt: new Date().toISOString(),
      generator: 'Built-in Procedural Preset',
      classification: 'percussive',
    },
    layers: [
      {
        id: 'hit-body',
        name: 'Thud Transient',
        enabled: true,
        solo: false,
        oscillatorType: 'triangle',
        startTime: 0,
        duration: 0.18,
        gain: 0.85,
        pan: 0,
        startFrequency: 320,
        endFrequency: 45,
        frequencyCurve: 'exponential',
        envelope: { attack: 0.001, decay: 0.12, sustain: 0.0, release: 0.05 },
        lowPassFilter: { enabled: true, cutoff: 600, q: 1.5 },
        highPassFilter: { enabled: false, cutoff: 30, q: 1 },
        distortion: { enabled: true, amount: 0.25 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 80, modDepth: 0 },
        seed: 771,
      },
      {
        id: 'hit-slap',
        name: 'Noise Impact Slap',
        enabled: true,
        solo: false,
        oscillatorType: 'noise',
        startTime: 0,
        duration: 0.09,
        gain: 0.65,
        pan: 0,
        startFrequency: 2000,
        endFrequency: 2000,
        frequencyCurve: 'constant',
        envelope: { attack: 0.001, decay: 0.05, sustain: 0.0, release: 0.03 },
        lowPassFilter: { enabled: true, cutoff: 3200, q: 2.2 },
        highPassFilter: { enabled: true, cutoff: 300, q: 1.2 },
        distortion: { enabled: true, amount: 0.35 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 100, modDepth: 0 },
        seed: 882,
      },
    ],
  },

  'small-explosion': {
    version: 1,
    name: 'Small Explosion',
    category: 'Combat',
    duration: 0.58,
    masterGain: 0.72,
    metadata: {
      createdAt: new Date().toISOString(),
      generator: 'Built-in Procedural Preset',
      classification: 'noisy',
    },
    layers: [
      {
        id: 'exp-sub-drop',
        name: 'Sub Boom',
        enabled: true,
        solo: false,
        oscillatorType: 'sine',
        startTime: 0,
        duration: 0.38,
        gain: 0.85,
        pan: 0,
        startFrequency: 170,
        endFrequency: 32,
        frequencyCurve: 'exponential',
        envelope: { attack: 0.002, decay: 0.28, sustain: 0.0, release: 0.08 },
        lowPassFilter: { enabled: true, cutoff: 400, q: 2 },
        highPassFilter: { enabled: false, cutoff: 20, q: 1 },
        distortion: { enabled: true, amount: 0.4 },
        delay: { enabled: false, time: 0.05, feedback: 0.2, mix: 0 },
        frequencyModulation: { enabled: false, modFrequency: 60, modDepth: 0 },
        seed: 101,
      },
      {
        id: 'exp-debris-noise',
        name: 'Noise Blast Blast',
        enabled: true,
        solo: false,
        oscillatorType: 'noise',
        startTime: 0,
        duration: 0.54,
        gain: 0.8,
        pan: 0,
        startFrequency: 1500,
        endFrequency: 1500,
        frequencyCurve: 'constant',
        envelope: { attack: 0.003, decay: 0.35, sustain: 0.05, release: 0.15 },
        lowPassFilter: { enabled: true, cutoff: 1400, q: 1.8 },
        highPassFilter: { enabled: true, cutoff: 90, q: 0.8 },
        distortion: { enabled: true, amount: 0.45 },
        delay: { enabled: true, time: 0.08, feedback: 0.4, mix: 0.25 },
        frequencyModulation: { enabled: false, modFrequency: 100, modDepth: 0 },
        seed: 202,
      },
    ],
  },
};
